package net.rsemlal.tisseos.queries.consts

object QueryParams {
  val format = "format"
  val key = "key"
  val network = "network"
  val lineId = "lineId"
  val displayTerminus = "displayTerminus"
  val srid = "srid"
  val bbox = "bbox"
  val displayLines = "displayLines"
  val displayCoordXY = "displayCoordXY"
  val terminusId = "terminusId"
  val sortByDistance = "sortByDistance"
  val number = "number"
  val displayDestinations = "displayDestinations"
  val stopAreaId = "stopAreaId"
  val operatorCode = "operatorCode"
  val stopPointId = "stopPointId"
  val displayRealTime = "displayRealTime"
  val contentFormat = "contentFormat"
  val displayImportantOnly = "displayImportantOnly"
  val lineShortName = "lineShortName"
  val coordinatesXY = "coordinatesXY"
  val maxDistance = "maxDistance"
  val displayBestPlace = "displayBestPlace"
  val displayOnlyStopAreas = "displayOnlyStopAreas"
  val displayOnlyRoads = "displayOnlyRoads"
  val displayOnlyAdresses = "displayOnlyAdresses"
  val displayOnlyPublicPlaces = "displayOnlyPublicPlaces"
  val displayOnlyCities = "displayOnlyCities"
}